# Generated by Django 3.2.13 on 2022-11-19 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Input',
        ),
    ]
